### ISSUE TITLE
zef says "Invalid json?" against .gitignore file when installing JSON::Tiny

### ISSUE THREAD

**Issue by Nick-OpusVL** [moritz/json#33]
Having trouble installing JSON::Tiny.  Admittedly could be a zef issue but I've not had it with others like URI.

```
$ zef install JSON::Tiny
===> Searching for: JSON::Tiny
Invalid json? File: /home/nick.booker/.zef/store/JSON-Tiny-1.0.tar.gz/JSON-Tiny-1.0/.gitignore
  in method new at /home/nick.booker/.rakudobrew/moar-nom/install/share/perl6/site/sources/A5AD657D251B9AB1F41CBA0E1BDE16347ADAE809 (Zef::Distribution::Local) line 14
  in method fetch at /home/nick.booker/.rakudobrew/moar-nom/install/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 186
  in sub MAIN at /home/nick.booker/.rakudobrew/moar-nom/install/share/perl6/site/sources/31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 149
  in block <unit> at /home/nick.booker/.rakudobrew/moar-nom/install/share/perl6/site/resources/0031ECC6124802A80F7B7B073C50D0A1694E3020 line 1
  in sub MAIN at /home/nick.booker/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/nick.booker/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef line 2
```

My Perl looks like this:

```
$ perl6 --version
This is Rakudo version 2017.08-79-g4b02b8aad built on MoarVM version 2017.08.1-103-g41e1b7ce
implementing Perl 6.c.
```

**Comment by moritz** [comment]
I suspect this is a bug in zef. @ugexe, can you confirm that?

**Comment by ugexe** [comment]
I would first suggest making sure you are using the latest version of zef. If this is as I suspect it is due to the options used when archiving - specifically including the *directory* entry for the parent prefix of the pm files. Old zef behavior relied on this directory being first in tar list file output, but has since been updated to search instead of assume the locations it needs.

You could also release a new version to cpan to work with older zef, but I'm not sure exactly how to invoke whatever option this is. I generally download the .tar.gz generated by github and rename it.

**Comment by Nick-OpusVL** [comment]
Thanks, upgrading zef fixed it.
